//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat
    {
        public int catID { get; set; }
        public string catName { get; set; }
        public Nullable<int> catAge { get; set; }
        public Nullable<int> ownerID { get; set; }
    }
}
